### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by liyangyang123** [WangShuo1143368701/WSLiveDemo#5]
FATAL EXCEPTION: main
                                                   Process: com.wangshuo.wslive.wslivedemo, PID: 17274
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wangshuo.wslive.wslivedemo/com.wangshuo.wslive.wslivedemo.LiveActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void me.lake.librestreaming.core.RESHardVideoCore.setVideoFilter(me.lake.librestreaming.filter.hardvideofilter.BaseHardVideoFilter)' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2439)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2499)
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void me.lake.librestreaming.core.RESHardVideoCore.setVideoFilter(me.lake.librestreaming.filter.hardvideofilter.BaseHardVideoFilter)' on a null object reference
                                                       at me.lake.librestreaming.client.RESVideoClient.setHardVideoFilter(RESVideoClient.java:395)
                                                       at me.lake.librestreaming.client.RESClient.setHardVideoFilter(RESClient.java:314)
                                                       at me.lake.librestreaming.ws.StreamLiveCameraView.setHardVideoFilter(StreamLiveCameraView.java:214)
                                                       at com.wangshuo.wslive.wslivedemo.LiveActivity.initLiveConfig(LiveActivity.java:51)
                                                       at com.wangshuo.wslive.wslivedemo.LiveActivity.onCreate(LiveActivity.java:31)
                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)

**Comment by AndMy** [comment]
貌似不支持5.0以下设备

**Comment by liyangyang123** [comment]
我的是6.0设备

**Comment by AndMy** [comment]
files.add(new GPUImageCompatibleFilter(new GPUImageBeautyFilter()));

**Comment by liyangyang123** [comment]
这个加到哪里？

**Comment by WangShuo1143368701** [comment]
偶现报错还是必现的呢？ debug一下是不是走到这里了？
      if (!isSucceed) {
            Log.w(TAG, "推流prepare方法返回false, 状态异常.");
            return;
        }
