### ISSUE TITLE
请问下

### ISSUE THREAD

**Issue by 904079904** [WangShuo1143368701/WSLiveDemo#6]
作者你好 
protected void drain() {
    	if (mMediaCodec == null) return;
        ByteBuffer[] encoderOutputBuffers = mMediaCodec.getOutputBuffers();
 mMediaCodec.getOutputBuffers() 这个会报
     java.lang.IllegalStateException
                                                                                    at android.media.MediaCodec.getOutputBuffers(MediaCodec.java:2966)
                                                                                    at me.lake.librestreaming.encoder.MediaEncoder.drain(MediaEncoder.java:272)
                                                                                    at me.lake.librestreaming.encoder.MediaEncoder.run(MediaEncoder.java:135)

我是这样操作的 我点击开始推流  然后 在点 开始录像 就报 这样的错误了， 如果 单纯的点击录像是不会报错的 ，   还有就是 开始录像 然后保存 录像  应该 isRecord 这个参数 在保存录像的时候点击一下就应该是false 了 为什么 还是要点2下 才是false

**Comment by WangShuo1143368701** [comment]
先点录像在点推流也是一样是吧？ 推流和录制都是硬编码，某些手机只能同时支持一路硬编码，可能是这个原因。 第二个点2下的已经修复，上次了
