### ISSUE TITLE
x86手机,在安卓5.1.1的系统init的时候出现这个错误该如何解决呢?

### ISSUE THREAD

**Issue by roybill** [WangShuo1143368701/WSLiveDemo#66]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xi.scc-2/base.apk"],nativeLibraryDirectories=[/data/app/com.xi.scc-2/lib/x86, /vendor/lib, /system/lib]]] couldn't find 

wangshuo: getSupportedVideoSizes==null

"librestreaming.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:366)
        at java.lang.System.loadLibrary(System.java:988)
        at me.lake.librestreaming.client.RESClient.<clinit>(RESClient.java:525)
        at me.lake.librestreaming.ws.StreamLiveCameraView.getRESClient(StreamLiveCameraView.java:59)
        at me.lake.librestreaming.ws.StreamLiveCameraView.init(StreamLiveCameraView.java:73)
        at com.xi.scc.my.LiveActivity.initView(LiveActivity.kt:34)
        at com.xi.scc.base.BaseActivity.onCreate(BaseActivity.kt:54)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by aacai** [comment]
人才

**Comment by aacai** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
